function dataSet = importFile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  DATASET = IMPORTFILE(FILE) reads data from the first worksheet in the
%  Microsoft Excel spreadsheet file named FILE.  Returns the data as a
%  table.
%
%  DATASET = IMPORTFILE(FILE, SHEET) reads from the specified worksheet.
%
%  DATASET = IMPORTFILE(FILE, SHEET, DATALINES) reads from the specified
%  worksheet for the specified row interval(s). Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  dataSet = importfile("/Users/juandiegoocampo/Documents/University/Control Engineering/Signals and Systems/Capstone Project/dataSet.xlsx", "COVID-19-geographic-disbtributi", [2, 20712]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 01-Jul-2020 07:21:31

%% Input handling

    % If no sheet is specified, read first sheet
    
    if nargin == 1 || isempty(sheetName)
        sheetName = 1;
    end

    % If row start and end points are not specified, define defaults
    
    if nargin <= 2
        dataLines = [2, 20712];
    end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 11);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":K" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["dateRep", "day", "month", "year", "cases", "deaths", "countriesAndTerritories", "geoId", "countryterritoryCode", "popData2018", "continentExp"];
opts.VariableTypes = ["datetime", "double", "double", "double", "double", "double", "categorical", "categorical", "categorical", "double", "categorical"];

% Specify variable properties
opts = setvaropts(opts, ["countriesAndTerritories", "geoId", "countryterritoryCode", "continentExp"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "dateRep", "InputFormat", "");

% Import the data
dataSet = readtable(workbookFile, opts, "UseExcel", false);

    for idx = 2:size(dataLines, 1)
        opts.DataRange = "A" + dataLines(idx, 1) + ":K" + dataLines(idx, 2);
        tb = readtable(workbookFile, opts, "UseExcel", false);
        dataSet = [dataSet; tb]; %#ok<AGROW>
    end

end