function [fitresult, gof] = createFit(timeFrame_test, cumulativeCases)
%CREATEFIT(TIMEFRAME_TEST,CUMULATIVECASES)
%  Create a fit.
%
%  Data for 'Cummulative Cases Fitted Curve' fit:
%      X Input : timeFrame_test
%      Y Output: cumulativeCases
%      Weights : cumulativeCases
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Jul-2020 09:36:12


%% Fit: 'Cummulative Cases Fitted Curve'.
[xData, yData, weights] = prepareCurveData( timeFrame_test, cumulativeCases, cumulativeCases );

% Set up fittype and options.
ft = fittype( 'gauss5' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0];
opts.Normalize = 'on';
opts.Robust = 'LAR';
opts.StartPoint = [95043 1.708973675637 0.0987452867541215 70703.949991248 1.52421976475732 0.103551909850056 54115.1980607233 1.33946585387765 0.109680753965659 42544.234341657 1.12391962451802 0.113130181730497 32226.041452773 0.908373395158404 0.121780790532969];
opts.Weights = weights;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Cummulative Cases Fitted Curve' );
h = plot( fitresult, xData, yData );
legend( h, 'cumulativeCases vs. timeFrame_test with cumulativeCases', 'Cummulative Cases Fitted Curve', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'timeFrame_test', 'Interpreter', 'none' );
ylabel( 'cumulativeCases', 'Interpreter', 'none' );
grid on


