function [fitresult, gof] = fittedPlot(timeFrame_test, cumulativeCases)
%CREATEFIT(TIMEFRAME_TEST,CUMULATIVECASES)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : timeFrame_test
%      Y Output: cumulativeCases
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Jul-2020 09:21:36


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( timeFrame_test, cumulativeCases );

% Set up fittype and options.
ft = fittype( 'gauss2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0];
opts.Robust = 'Bisquare';
opts.StartPoint = [95043 112 8.01703895879352 48559.597086643 98 9.39957194368251];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'cumulativeCases vs. timeFrame_test', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'timeFrame_test', 'Interpreter', 'none' );
ylabel( 'cumulativeCases', 'Interpreter', 'none' );
grid on


