function ColombiaCOVID19 = importCSV(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  COLOMBIACOVID19 = IMPORTFILE1(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  COLOMBIACOVID19 = IMPORTFILE1(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  ColombiaCOVID19 = importfile1("/Users/juandiegoocampo/Documents/University/Control Engineering/Signals and Systems/Capstone Project/Colombia_COVID19.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 02-Jul-2020 16:56:57

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "NUEVOS_CASOS", "TOTAL_CASOS", "TOTAL_MUERTES", "TOTAL_RECUPERADOS", "FECHA_ACTUALIZACION", "Var7", "NUEVOS_MUERTOS", "NUEVO_RECUPERADOS"];
opts.SelectedVariableNames = ["NUEVOS_CASOS", "TOTAL_CASOS", "TOTAL_MUERTES", "TOTAL_RECUPERADOS", "FECHA_ACTUALIZACION", "NUEVOS_MUERTOS", "NUEVO_RECUPERADOS"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "datetime", "string", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var7"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var7"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "FECHA_ACTUALIZACION", "InputFormat", "dd-MMM-yyyy HH:mm:ss");

% Import the data
ColombiaCOVID19 = readtable(filename, opts);

end